import { afterEach, describe, expect, it, vi } from 'vitest'
import { SpeechSynthesisController, VOICE_DISCOVERY_TIMEOUT_MS, type UseSpeechSynthesisOptions } from './useSpeechSynthesis'
import { FakeSpeechSynthesisPort } from '@/lib/reader/speech/FakeSpeechSynthesisPort'
import type { SpeechSegment, SpeechSettings, SpeechVoice } from '@/lib/reader/speech/types'

const local: SpeechVoice = { voiceURI: 'local-ja', name: 'Japanese', lang: 'ja-JP', localService: true, default: true }
const remote: SpeechVoice = { ...local, voiceURI: 'remote-ja', name: 'Remote', localService: false }
const settings = (): SpeechSettings => ({ rate: 1, continueAcrossPages: true, voiceByLanguage: {}, allowRemoteVoiceByLanguage: {} })
const segment = (pageIndex: number, blockIndex = 0): SpeechSegment => ({ id: `${pageIndex}:${blockIndex}`, pageIndex, blockIndex, text: `本文${pageIndex}-${blockIndex}`, lang: 'ja-JP', kind: 'paragraph' })
const controllers: SpeechSynthesisController[] = []
function setup(pages: SpeechSegment[][] = [[segment(0), segment(0, 1)], [segment(1)]], overrides: Partial<UseSpeechSynthesisOptions> = {}, voices = [local]) {
  const port = new FakeSpeechSynthesisPort()
  port.voices = voices
  const onNavigate = vi.fn()
  const onPlaybackStart = vi.fn()
  const options = { pages, language: 'ja', settings: settings(), contextKey: 'book-ja-vertical', onNavigate, onPlaybackStart, ...overrides }
  const controller = new SpeechSynthesisController(options, port)
  controllers.push(controller)
  controller.mount()
  return { controller, port, options, onNavigate, onPlaybackStart }
}
afterEach(() => { controllers.forEach(controller => controller.dispose()); controllers.length = 0; vi.useRealTimers() })

describe('speech session ownership', () => {
  it('does not speak during mount or options updates; first speak occurs inside start', () => {
    const { controller, port, options, onPlaybackStart } = setup()
    controller.updateOptions(options)
    expect(port.requests).toHaveLength(0)
    controller.start(0)
    expect(port.requests).toHaveLength(1)
    expect(onPlaybackStart).toHaveBeenCalledOnce()
    expect(port.cancelCount).toBe(1)
    expect(controller.getSnapshot().status).toBe('playing')
    port.emitStart()
    expect(port.requests).toHaveLength(1)
    port.emitEnd()
    expect(port.requests).toHaveLength(2)
    expect(controller.getSnapshot().cursor.segmentIndex).toBe(1)
  })
  it('consumes each normal end once and waits for matching page confirmation', () => {
    const { controller, port, onNavigate } = setup()
    controller.start(0)
    port.emitEnd(0)
    port.emitEnd(0)
    expect(port.requests).toHaveLength(2)
    port.emitEnd(1)
    expect(onNavigate).toHaveBeenCalledOnce()
    const [page, token] = onNavigate.mock.calls[0]
    expect(controller.notifyNavigation(page, 'speech', token)).toBe(true)
    expect(controller.confirmPage(page, 'incorrect')).toBe(false)
    expect(port.requests).toHaveLength(2)
    expect(controller.confirmPage(page, token)).toBe(true)
    expect(controller.confirmPage(page, token)).toBe(false)
    expect(port.requests).toHaveLength(3)
    port.emitEnd()
    expect(controller.getSnapshot().status).toBe('completed')
  })
  it.each(['user', 'restore'] as const)('invalidates speech navigation when %s wins in the same tick', source => {
    const { controller, port, onNavigate } = setup([[segment(0)], [segment(1)]])
    controller.start(0)
    port.emitEnd()
    const [page, token] = onNavigate.mock.calls[0]
    controller.notifyNavigation(0, source)
    expect(controller.confirmPage(page, token)).toBe(false)
    port.emitEnd(0)
    expect(port.requests).toHaveLength(1)
    expect(controller.getSnapshot().cursor).toEqual({ pageIndex: 0, segmentIndex: 0 })
  })
  it('invalidates before synchronous cancel errors and ignores delayed events', () => {
    const { controller, port, onNavigate } = setup()
    controller.start(0)
    port.onCancel = () => port.emitError('interrupted', 0)
    controller.stop(1)
    port.emitEnd(0)
    port.emitError('network', 0)
    expect(controller.getSnapshot().status).toBe('ready')
    expect(controller.getSnapshot().error).toBeNull()
    expect(onNavigate).not.toHaveBeenCalled()
    expect(port.requests).toHaveLength(1)
  })
  it.each(['text-too-long', 'voice-unavailable', 'language-unavailable', 'audio-busy', 'not-allowed', 'network', 'synthesis-failed', 'canceled', 'interrupted'])('holds the failing cursor for %s and retries only on a new play action', code => {
    const { controller, port, onNavigate } = setup()
    controller.start(0)
    port.emitEnd(0)
    port.emitError(code, 1)
    const cursor = controller.getSnapshot().cursor
    expect(cursor).toEqual({ pageIndex: 0, segmentIndex: 1 })
    expect(controller.getSnapshot().status).toBe('errorStopped')
    port.emitEnd(1)
    controller.reconcileVisibility(true)
    expect(port.requests).toHaveLength(2)
    expect(onNavigate).not.toHaveBeenCalled()
    controller.start(0)
    expect(port.requests[2].request.text).toBe(port.requests[1].request.text)
    expect(controller.getSnapshot().cursor).toEqual(cursor)
  })
  it('stops when rate, voice, context, language, or page plans change', () => {
    const { controller, port, options } = setup()
    controller.start(0)
    controller.updateOptions({ ...options, settings: { ...options.settings, rate: 1.5 } })
    port.emitEnd(0)
    expect(port.requests).toHaveLength(1)
    controller.start(0)
    expect(port.requests[1].request.rate).toBe(1.5)
    controller.updateOptions({ ...options, contextKey: 'another-mode' })
    port.emitEnd(1)
    expect(controller.getSnapshot().status).toBe('ready')
    expect(port.requests).toHaveLength(2)
  })
  it('pause/resume neither creates a new utterance nor auto resumes on stop', () => {
    const { controller, port } = setup()
    controller.start(0)
    controller.pause()
    expect(controller.getSnapshot().status).toBe('paused')
    controller.resume()
    expect(port.resumeCount).toBe(2)
    expect(port.requests).toHaveLength(1)
    controller.stop()
    controller.resume()
    expect(port.requests).toHaveLength(1)
  })
  it('clears native paused state on a new user play after pause and stop', () => {
    const { controller, port } = setup()
    controller.start(0)
    controller.pause()
    controller.stop()
    expect(port.status.paused).toBe(true)
    controller.start(0)
    expect(port.status.paused).toBe(false)
    expect(port.requests).toHaveLength(2)
  })
  it('defers a normal end arriving while paused until explicit resume', () => {
    const { controller, port } = setup()
    controller.start(0)
    controller.pause()
    port.emitEnd()
    expect(port.requests).toHaveLength(1)
    controller.resume()
    expect(port.requests).toHaveLength(2)
  })
  it('defers a committed page while paused until explicit resume', () => {
    const { controller, port, onNavigate } = setup([[segment(0)], [segment(1)]])
    controller.start(0)
    port.emitEnd()
    controller.pause()
    const [page, token] = onNavigate.mock.calls[0]
    controller.confirmPage(page, token)
    expect(port.requests).toHaveLength(1)
    controller.resume()
    expect(port.requests).toHaveLength(2)
  })
})

describe('finite empty-page traversal', () => {
  it('skips consecutive empty pages once at a normal boundary', () => {
    const { controller, port, onNavigate } = setup([[segment(0)], [], [], [segment(3)], []])
    controller.start(0)
    port.emitEnd()
    expect(onNavigate.mock.calls[0][0]).toBe(3)
    controller.confirmPage(3, onNavigate.mock.calls[0][1])
    port.emitEnd()
    expect(controller.getSnapshot().status).toBe('completed')
    expect(onNavigate).toHaveBeenCalledOnce()
  })
  it('resolves an empty start and performs its first speak inside the user action', () => {
    const { controller, port, onNavigate } = setup([[], [], [segment(2)]])
    controller.start(0)
    expect(onNavigate.mock.calls[0][0]).toBe(2)
    expect(port.requests).toHaveLength(1)
    controller.confirmPage(2, onNavigate.mock.calls[0][1])
    expect(port.requests).toHaveLength(1)
  })
  it.each([{ pages: [] }, { pages: [[]] }, { pages: [[], [], []] }])('finishes an entirely empty plan without looping: %j', ({ pages }) => {
    const { controller, port, onNavigate } = setup(pages)
    controller.start(0)
    expect(controller.getSnapshot().status).toBe('completed')
    expect(port.requests).toHaveLength(0)
    expect(onNavigate).not.toHaveBeenCalled()
  })
  it('does not traverse empty or completed pages when continuation is off', () => {
    const { controller, port, onNavigate } = setup([[], [segment(1)]], { settings: { ...settings(), continueAcrossPages: false } })
    controller.start(0)
    expect(controller.getSnapshot().status).toBe('completed')
    expect(port.requests).toHaveLength(0)
    expect(onNavigate).not.toHaveBeenCalled()
    controller.start(1)
    port.emitEnd()
    expect(onNavigate).not.toHaveBeenCalled()
  })
})

describe('voice discovery and lifecycle', () => {
  it.each([
    [local], [{ ...local, lang: 'en-US' }], [remote],
  ])('rejects a new UA default trial whenever a voice list is available: %j', voice => {
    const { controller, port } = setup(undefined, {}, [voice])
    controller.start(0, { uaDefault: true })
    expect(port.requests).toHaveLength(0)
  })
  it('waits for delayed voices, has one subscription, and survives StrictMode cleanup/remount', () => {
    vi.useFakeTimers()
    const { controller, port } = setup(undefined, {}, [])
    expect(controller.getSnapshot().status).toBe('loadingVoices')
    controller.start(0)
    expect(port.requests).toHaveLength(0)
    controller.dispose()
    expect(port.listeners.size).toBe(0)
    expect(vi.getTimerCount()).toBe(0)
    controller.mount()
    expect(port.listeners.size).toBe(1)
    port.setVoices([local])
    expect(controller.getSnapshot().status).toBe('ready')
    expect(vi.getTimerCount()).toBe(0)
    expect(port.requests).toHaveLength(0)
  })
  it('allows an explicit unknown-location UA default trial only after finite discovery', () => {
    vi.useFakeTimers()
    const { controller, port } = setup(undefined, {}, [])
    controller.start(0, { uaDefault: true })
    expect(port.requests).toHaveLength(0)
    vi.advanceTimersByTime(VOICE_DISCOVERY_TIMEOUT_MS)
    expect(controller.getSnapshot().voiceStatus).toBe('unavailable')
    controller.start(0)
    expect(port.requests).toHaveLength(0)
    controller.start(0, { uaDefault: true })
    expect(port.requests[0].request.voiceURI).toBeUndefined()
    expect(port.requests[0].request.lang).toBe('ja-JP')
    port.emitStart()
    expect(controller.getSnapshot().status).toBe('playing')
    port.emitError('not-allowed')
    expect(controller.getSnapshot().status).toBe('errorStopped')
    expect(port.requests).toHaveLength(1)
  })
  it('never automatically selects a remote voice', () => {
    const { controller, port, options } = setup(undefined, {}, [remote])
    controller.start(0)
    expect(port.requests).toHaveLength(0)
    controller.updateOptions({ ...options, settings: { ...options.settings,
      voiceByLanguage: { ja: { ...remote, mode: 'listed' } }, allowRemoteVoiceByLanguage: { ja: true } } })
    controller.start(0)
    expect(port.requests[0].request.voiceURI).toBe(remote.voiceURI)
  })
  it('stops at the current cursor if its voice disappears instead of silently switching', () => {
    const { controller, port } = setup()
    controller.start(0)
    port.setVoices([{ ...local, voiceURI: 'replacement' }])
    expect(controller.getSnapshot().status).toBe('playing')
    port.emitEnd()
    expect(controller.getSnapshot().status).toBe('errorStopped')
    expect(controller.getSnapshot().cursor.segmentIndex).toBe(0)
    expect(port.requests).toHaveLength(1)
    controller.start(0)
    expect(port.requests[1].request.voiceURI).toBe('replacement')
  })
  it.each([
    { speaking: true, pending: false, paused: false },
    { speaking: false, pending: true, paused: false },
    { speaking: true, pending: false, paused: true },
  ])('preserves active native speech at visible return: %j', status => {
    const { controller, port } = setup()
    controller.start(0)
    const generation = controller.getSnapshot().generation
    port.status = status
    controller.reconcileVisibility(false)
    expect(port.statusReadCount).toBe(0)
    controller.reconcileVisibility(true)
    expect(port.statusReadCount).toBe(1)
    expect(controller.getSnapshot().generation).toBe(generation)
    expect(port.requests).toHaveLength(1)
  })
  it.each([false, true])('holds cursor when speech vanished at visible return (native paused=%s)', paused => {
    const { controller, port } = setup()
    controller.start(0)
    port.emitEnd(0)
    port.status = { speaking: false, pending: false, paused }
    controller.reconcileVisibility(true)
    expect(controller.getSnapshot().status).toBe('ready')
    expect(controller.getSnapshot().cursor.segmentIndex).toBe(1)
    port.emitEnd(1)
    expect(port.requests).toHaveLength(2)
    controller.start(0)
    expect(port.requests[2].request.text).toBe(port.requests[1].request.text)
  })
  it('does not update subscribers or speak after disposal', () => {
    const { controller, port } = setup()
    const listener = vi.fn()
    controller.subscribe(listener)
    controller.start(0)
    controller.dispose()
    listener.mockClear()
    port.emitEnd(0)
    port.emitError('network', 0)
    port.setVoices([])
    controller.reconcileVisibility(true)
    expect(listener).not.toHaveBeenCalled()
    expect(port.requests).toHaveLength(1)
  })
  it('keeps an unsupported API inert', () => {
    const port = new FakeSpeechSynthesisPort()
    port.supported = false
    const { options } = setup()
    const controller = new SpeechSynthesisController(options, port)
    controllers.push(controller)
    controller.mount()
    controller.start(0)
    expect(controller.getSnapshot().status).toBe('unsupported')
    expect(port.requests).toHaveLength(0)
    expect(port.listeners.size).toBe(0)
  })
})


describe('speech seeking', () => {
  it('replaces an utterance at the selected offset and ignores its late events', () => {
    const { controller, port } = setup()
    controller.start(0)
    controller.seek(0, 1, 2)
    expect(port.requests[1].request.text).toBe('0-1')
    port.requests[0].events.onBoundary?.(4)
    port.emitEnd(0)
    expect(port.requests).toHaveLength(2)
    expect(controller.getSnapshot().charIndex).toBe(2)
    port.requests[1].events.onBoundary?.(1)
    expect(controller.getSnapshot().charIndex).toBe(3)
    expect(controller.getSnapshot().status).toBe('playing')
  })
})
